services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multimodal-medical-ai
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: bash
    environment:
      PYTHONUNBUFFERED: "1"
      TOKENIZERS_PARALLELISM: "false"
